### ISSUE TITLE
Tab instead of a Dropdown List

### ISSUE THREAD

**Issue by 5axes** [fieldOfView/Cura-TabbedSettingsPlugin#1]
Hello @fieldOfView, this issue is more an open discussion than a request but It could be a nice feature. 
Yesterday I've seen a post of [@ChuckHellebuyck](https://twitter.com/ChuckHellebuyck)  concerning the modification of the interface of Cura made by Qidi on their ["Cura" "Qidi Print" version](https://twitter.com/ChuckHellebuyck/status/1531660625314824192)

![image](https://user-images.githubusercontent.com/11015345/171366793-c92e6f90-b680-4457-ad19-8aef6ea07ca6.png)

And I'm agree with the comment of several users. Using a Tab System instead of this DropDown menu could bring a better user experience.

Personnaly I'm using a lot, the  right hidden menu to "Collapse All Categories" To reduce the size of the list and symplify the navigation in the parameters list. 
![image](https://user-images.githubusercontent.com/11015345/171367863-da169175-4444-4580-a85e-a5420c82a3eb.png)

Using a Tab System with only the parameters of the section would simplify the navigation.  Something like :

![image](https://user-images.githubusercontent.com/11015345/171369758-c5dc287b-5f79-40ee-bcc0-855f181581b4.png)

**Comment by 5axes** [comment]
[Qidi Print 6.2.1](http://www.qd3dprinter.com/software/)
Three interesting things. The interface and the creation of the Ooze  shield or the Prime Tower as a geometrical element

https://user-images.githubusercontent.com/11015345/171430838-82f6b006-a957-4246-862a-47bbf83b2d68.mp4

And also in the menu The example model to replace the Calibration Plugin

**Comment by 5axes** [comment]
The Search Function. In this case I would prefer to have a global list of parameters and not visible only in each individual Section. This point is less effective.




https://user-images.githubusercontent.com/11015345/171433767-b23b73b4-bcd1-445e-9089-131db4ca7162.mp4

**Comment by 5axes** [comment]
An other Nice little feature. Right clic on the extruder Tab to change the color.

https://user-images.githubusercontent.com/11015345/171437778-0cc10fd7-146e-4a01-b9ac-52bff1effcb2.mp4

**Comment by fieldOfView** [comment]
I am transferring this to my general Cura-Plugins repository, because this falls outside the scope of the Sidebar GUI plugin.

A plugin that changes the settings view to an "accordion" type, or a vertical tab list, has been on my list of possible plugins for a while.

**Comment by fieldOfView** [comment]
Said plugin would work with or without sidebargui.

Also see fieldOfView/Cura-Plugins#10

**Comment by fieldOfView** [comment]
> An other Nice little feature. Right clic on the extruder Tab to change the color.

> The interface and the creation of the Ooze shield or the Prime Tower as a geometrical element

This has nothing to do with the settings list. Please keep issues on topic.

**Comment by 5axes** [comment]
Realy great Idea this **_Changed Settings_** Tabs

![image](https://user-images.githubusercontent.com/11015345/231212314-510f4c89-f5ac-4735-825b-8360398b4022.png)

But the **_parameter search function_** is a function that should be kept  as well as the possibility to filter the parameters via  some lists .

![image](https://user-images.githubusercontent.com/11015345/231214405-80750ec1-3f68-4e7b-adb0-00307256676b.png)
