### ISSUE TITLE
Wish can be used on Cura-3.14

### ISSUE THREAD

**Issue by TomonoTzeng** [fieldOfView/Cura-TabbedSettingsPlugin#11]
This wonderful plugin wish can be used on ver. 3.14.
Please!
And Thank's!

**Comment by fieldOfView** [comment]
Thanks for your kind words. 

In order for the Tabbed Settings plugin to work, it does quite a bit of "nasty" patching of the original interface. These patches may break the interface when the original interface is changed, so I have to spend some work with each new version of Cura that gets released. Supporting older versions, let alone version that have been adapted by 3rd parties, is an exorbitant amount of work. I would have to rewrite the entire plugin to work with the Cura version you use.

Unfortunately, this is just not feasible. I hope you understand.

**Comment by fieldOfView** [comment]
Edit: I think you mean 4.13. 

In Cura 5, Ultimaker switched to a major new version of the Qt GUI framework, which meant that every single bit of UI-related code was rewritten. So even with Cura 4.13, unfortunately I cannot afford the time to rewrite the plugin.

**Comment by TomonoTzeng** [comment]
OK! I see.
Thank you for your reply.
