### ISSUE TITLE
Add compatibility with Cura 5.7.0

### ISSUE THREAD

**Issue by eccodolf** [fieldOfView/Cura-TabbedSettingsPlugin#12]
Due to new release of Cura 5.7.0 new release of plugin is neened. 

![image](https://github.com/fieldOfView/Cura-TabbedSettingsPlugin/assets/37067660/93f73bc5-8a0d-47bc-b099-4f060570d4e2)

**Comment by fieldOfView** [comment]
Closing as a duplicate of #10. 

See https://github.com/fieldOfView/Cura-TabbedSettingsPlugin/releases
