### ISSUE TITLE
v0.2.0-DEV Weird issue with the search Function

### ISSUE THREAD

**Issue by 5axes** [fieldOfView/Cura-TabbedSettingsPlugin#2]
When I use the search function in the last version, some panels don't show any parameter anymore.

![UltiMaker-Cura_8b0jL8NgOf](https://user-images.githubusercontent.com/11015345/234342116-402dd77e-26a2-4a63-bfc5-a8dd2e9187f5.gif)
[cura.log](https://github.com/fieldOfView/Cura-TabbedSettingsPlugin/files/11324752/cura.log)

**Comment by fieldOfView** [comment]
Good find. I can reproduce this.
