### ISSUE TITLE
Option to turn off the ToolTips

### ISSUE THREAD

**Issue by GregValiant** [fieldOfView/Cura-TabbedSettingsPlugin#5]
Hi Aldo,
After using the plugin for a while (it's terrific) I have found that the ToolTips of the various settings get in the way of the tab buttons.  Would it be possible to toggle the ToolTips on/off (maybe "hoverEnabled" true or false)?

I have to slide the mouse all over the place to dismiss them.
![image](https://github.com/fieldOfView/Cura-TabbedSettingsPlugin/assets/64202104/8ad048c1-bd53-4968-b4e0-809784fc052c)

**Comment by GregValiant** [comment]
After looking at this a bit more I went into "TabbedSettingsView.qml" and found that by switching "true" to "false" in lines 645 and 648 the effect is just what I wanted.  The Tooltips now show when the frame is undocked and do not show when it is docked.  It is simply the opposite of the current behavior.  The tooltips no longer hide the tabbed icons.
645   if(sidebargui_docked === false) >>> gets changed to "true"
648   else if(sidebargui_docked === true) >>> gets changed to "false"

A problem would be that the user has no way to tell why there are no tooltips.
If the SidebarGUI button for docking and undocking had a Tooltip like "Undock to show tooltips" it might be nice.
The current behavior is that when undocked there is no mention of why there are no tooltips.  Not adding an "Undock to show tooltips" balloon wouldn't really make any difference.
![Tooltip Suggestion](https://github.com/fieldOfView/Cura-TabbedSettingsPlugin/assets/64202104/fd70facd-8169-456e-a991-102d8d810502)

I would put in a PR but it took me 9 months to get to this point.

**Comment by fieldOfView** [comment]
Hey, I am sorry I never responded to this issue. I must say I don't quite get the issue. I move my mouse to the "gutter"/margin on either side of the settings and the tooltip disappears, as expected. When the tooltip obscures the tab, I just need to make a micro-pause on my way to the tabbar on the space between the setting label and the tab row.

Your proposed "Undock to show tooltips" is not an acceptable option for me, UX-wise. It is the wrong solution for the problem.

**Comment by GregValiant** [comment]
Thanks Aldo.
Maybe it's just an issue for me because of the small screen on this laptop.  It always seemed like I was moving the mouse all over to get the tooltip to dismiss.  The alteration I made does what I wanted.  I didn't consider it a problem, more of a personal annoyance.
I'll go ahead and close this.

**Comment by fieldOfView** [comment]
> It always seemed like I was moving the mouse all over to get the tooltip to dismiss.

Is this mitigated by moving the mouse into that gutter?

**Comment by GregValiant** [comment]
You made me change it back.
When I carefully move to the gutter and stop there, the tooltip dismisses.  If I miss it to the right, the next tooltip jumps up.  If I go to far to the left, the tooltip doesn't dismiss.  It's like a dance and I can't remember the steps.  If I move the cursor way to the left the tooltip dismisses and then I can slide back and hit the next tab button that I want.
In the image is a big tooltip and it covers several tab buttons.  On this computer the "gutter" is about 2 pixels wide and when I slide across it the tooltip flashes and re-appears, or the next tooltip appears, something annoying.  It is rare for me to land the cursor in the sweet spot and stop it there to let the tooltip go away.  (I had to draw the cursor at it's location in this screenshot.)  Hovering over the tooltip insures that it doesn't go away.
![TabbedTooltip](https://github.com/fieldOfView/Cura-TabbedSettingsPlugin/assets/64202104/98298b77-c88a-41e6-915b-76b1a08769ac)

Changing true to false and false to true was simple and easy to understand.  I'm not happy that it took me so long to figure it out, but better late than never.
