### ISSUE TITLE
Can't save or select profile

### ISSUE THREAD

**Issue by terachip** [fieldOfView/Cura-TabbedSettingsPlugin#6]
Awesome plugin, but when it's active I'm not able to select other print profiles or save the changes I made.

**Comment by fieldOfView** [comment]
Thanks for reporting this.  Could you help test this fix?
https://github.com/fieldOfView/Cura-TabbedSettingsPlugin/releases/tag/v1.0.1

Download the .curapackage and drop it onto the buildplate in Cura as if you were opening a 3d model.

**Comment by fieldOfView** [comment]
The fixed release is now available in the marketplace.
