### ISSUE TITLE
Dual Extruder

### ISSUE THREAD

**Issue by alex09134** [fieldOfView/Cura-TabbedSettingsPlugin#8]
Unless I did not find the proper solution that exists, it seems that with dual extrusions setup the "TabbedSettingPluging" is showing only one extruder, the first, hiding the second one.
my mistake?

**Comment by fieldOfView** [comment]
Sorry it took me a while to get to this. You are quite right, thanks for bringing this to my attention.

The issue slipped my attention because I use the plugin in tandem with the Sidebar GUI plugin. In combination with that plugin, the extruder tabs do show up. I'll fix this ASAP.

**Comment by fieldOfView** [comment]
A prerelease with a fix is available here:
https://github.com/fieldOfView/Cura-TabbedSettingsPlugin/releases/tag/v1.0.4-DEV

Download the .curapackage and drop it onto the cura buildplate as if you were opening a 3d model.
