### ISSUE TITLE
Plugin doesn't work in Cura 5.5 version

### ISSUE THREAD

**Issue by jasoncroog** [fieldOfView/Cura-TabbedSettingsPlugin#9]
Hello,

First of all, plugin is amazing. At the beginning it was hard to change thinking but now it doesn't work in Cura 5.5 version and it's like without a hand.
![5 5 doesnt work](https://github.com/fieldOfView/Cura-TabbedSettingsPlugin/assets/75775199/02ee7263-0798-4bb6-b981-3b931aac9608)
Of course I have been trying re-installing, removing and still doesn't work.

**Comment by 5axes** [comment]
I'm not sure I can help you. I don't have any problems myself. Sometimes using other plugins such as Sidebar Gui can cause issues.

You must have a look in the log file to find any clues for the origin of this problem.

**Comment by fieldOfView** [comment]
A version compatible with Cura 5.5 is available in the Marketplace. A version compatible with Cura 5.6 is in prerelease.

See #10 for why this happens.
